/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get server health status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all emails with pagination */
        get: {
            parameters: {
                query?: {
                    imap_config_id?: number;
                    page?: number;
                    labels?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["EmailsListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{imap_uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific email by IMAP UID */
        get: {
            parameters: {
                query: {
                    /** @description IMAP config ID to filter emails */
                    imap_config_id: number;
                };
                header?: never;
                path: {
                    /** @description IMAP UID of the email */
                    imap_uid: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["EmailDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex all emails by reapplying rules and categories */
        post: {
            parameters: {
                query?: {
                    /** @description Optional IMAP config ID to reindex only specific account emails */
                    imap_config_id?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ReindexResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imap-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all IMAP configurations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ImapConfigListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a new IMAP configuration */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreateImapConfigRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ImapConfigDetailResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imap-configs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an existing IMAP configuration */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["UpdateImapConfigRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["ImapConfigDetailResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an IMAP configuration */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all email rules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["RuleListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a new email rule */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreateRuleRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an existing email rule */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["UpdateRuleRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an email rule */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["MessageResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{uid}/categorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually categorize a specific email by IMAP UID */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uid: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["CategorizeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all pages for a user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["PageListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/detail/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single page by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["PageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{user_id}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single page by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["PageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new page */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreatePageRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["PageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update an existing page */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["UpdatePageRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["PageResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a page */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["PageMessageResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategorizeResponse */
        CategorizeResponse: {
            /** Format: uint64 */
            actions_applied: number;
        };
        /**
         * CreateImapConfigRequest
         * @description Request to create a new IMAP configuration
         */
        CreateImapConfigRequest: {
            name: string;
            mail_host: string;
            /** Format: uint16 */
            mail_port: number;
            username: string;
            password: string;
            /** @default true */
            use_tls: boolean;
        };
        /**
         * CreatePageRequest
         * @description Request to create a new page
         */
        CreatePageRequest: {
            user_id: string;
            name: string;
            slug: string;
            category?: string;
            page_type: string;
            config: string;
            /** Format: int64 */
            position: number;
        };
        /** CreateRuleRequest */
        CreateRuleRequest: {
            name: string;
            condition: unknown;
            actions: unknown[];
            /** Format: int32 */
            priority: number;
            enabled: boolean;
        };
        /** EmailDetailResponse */
        EmailDetailResponse: {
            email: components["schemas"]["EmailResponse"];
        };
        /**
         * EmailListItem
         * @description Simplified email for list view
         */
        EmailListItem: {
            /** Format: int64 */
            imap_uid: number;
            subject?: string;
            from_address?: string;
            to_address?: string;
            created_at: string;
            /** Format: int64 */
            imap_config_id: number;
            labels: string[];
            /** Format: int64 */
            priority?: number;
        };
        /**
         * EmailResponse
         * @description API-friendly email representation with RFC3339 datetime strings
         */
        EmailResponse: {
            /** Format: int64 */
            imap_uid: number;
            message_id?: string;
            subject?: string;
            from_address?: string;
            to_address?: string;
            cc_address?: string;
            bcc_address?: string;
            reply_to?: string;
            date_sent?: string;
            date_maildog_fetched: string;
            body_text?: string;
            body_html?: string;
            raw_message?: string;
            flags?: string;
            /** Format: int64 */
            size_bytes?: number;
            has_attachments?: boolean;
            folder_name?: string;
            created_at: string;
            updated_at: string;
            /** Format: int64 */
            imap_config_id: number;
            labels: string[];
            /** Format: int64 */
            priority?: number;
        };
        /** EmailsListResponse */
        EmailsListResponse: {
            emails: components["schemas"]["EmailListItem"][];
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            page_size: number;
        };
        /** HealthResponse */
        HealthResponse: {
            status: string;
            version: string;
        };
        /**
         * ImapConfigDetailResponse
         * @description Response containing a single IMAP config
         */
        ImapConfigDetailResponse: {
            config: components["schemas"]["ImapConfigResponse"];
        };
        /**
         * ImapConfigListResponse
         * @description Response containing a list of IMAP configs
         */
        ImapConfigListResponse: {
            configs: components["schemas"]["ImapConfigResponse"][];
        };
        /**
         * ImapConfigResponse
         * @description API-friendly IMAP config representation (without encrypted password)
         */
        ImapConfigResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            mail_host: string;
            /** Format: int64 */
            mail_port: number;
            username: string;
            use_tls: boolean;
            created_at: string;
            updated_at: string;
        };
        /** MessageResponse */
        MessageResponse: {
            message: string;
        };
        /**
         * PageListResponse
         * @description Response containing a list of pages
         */
        PageListResponse: {
            pages: components["schemas"]["PageResponse"][];
        };
        /**
         * PageMessageResponse
         * @description Response for successful page operations
         */
        PageMessageResponse: {
            message: string;
        };
        /**
         * PageResponse
         * @description API-friendly Page representation
         */
        PageResponse: {
            slug: string;
            user_id: string;
            name: string;
            category?: string;
            page_type: string;
            config: string;
            /** Format: int64 */
            position: number;
            created_at: string;
            updated_at: string;
        };
        /**
         * ReindexResponse
         * @description Response for email reindexing operation
         */
        ReindexResponse: {
            message: string;
            /** Format: int64 */
            total_emails: number;
            /** Format: int64 */
            processed_emails: number;
            /** Format: int64 */
            failed_emails: number;
            /** Format: int64 */
            cleared_emails: number;
        };
        /** RuleListResponse */
        RuleListResponse: {
            rules: components["schemas"]["RuleResponse"][];
            /** Format: uint64 */
            total: number;
        };
        /** RuleResponse */
        RuleResponse: {
            id: string;
            name: string;
            condition: unknown;
            actions: unknown[];
            /** Format: int32 */
            priority: number;
            enabled: boolean;
        };
        /**
         * SuccessResponse
         * @description Success message response
         */
        SuccessResponse: {
            message: string;
        };
        /**
         * UpdateImapConfigRequest
         * @description Request to update an existing IMAP configuration
         */
        UpdateImapConfigRequest: {
            name?: string;
            mail_host?: string;
            /** Format: uint16 */
            mail_port?: number;
            username?: string;
            password?: string;
            use_tls?: boolean;
        };
        /**
         * UpdatePageRequest
         * @description Request to update a page
         */
        UpdatePageRequest: {
            name: string;
            slug: string;
            category?: string;
            page_type: string;
            config: string;
            /** Format: int64 */
            position: number;
        };
        /** UpdateRuleRequest */
        UpdateRuleRequest: {
            name: string;
            condition: unknown;
            actions: unknown[];
            /** Format: int32 */
            priority: number;
            enabled: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
