[package]
name = "maildog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
dotenvy = "0.15.7"
poem = { version = "3.0.4", features = ["session"] }
poem-openapi = "5.1.3"
rand = "0.8.5"
reqwest = "0.12.9"
serde = "1.0.209"
serde_json = "1.0.127"
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "sqlite", "time", "migrate", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
time = { version = "0.3", features = ["serde", "formatting", "parsing"] }
thiserror = "2.0.3"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
rusqlite = "=0.32.1"
url = { version = "2.5.7", features = ["serde"] }
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }
imap = "3.0.0-alpha.14"
regex = "1.10.6"
uuid = { version = "1.10.0", features = ["v4"] }
anyhow = "1.0"
mail-parser = "0.9"
aes-gcm = "0.10"
sha2 = "0.10"
